# "service" is the name of this project. This will also be added to your AWS resource names.
service: nanostores

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectTagging"
        - "s3:GetObject"
      Resource: "*"

package:
  individually: true # Packages each function individually
  exclude:
    - node_modules/** # Exclude initially to avoid redundancy
  include:
    - node_modules/** # Include the entire node_modules directory for each function
    - src/** # Include your source files

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /test
          method: get

  testRetrieveAudio:
    handler: src/audio/testRetrieveAudio.testReturnAudio
    events:
      - httpApi:
          path: /test/audio
          method: post

  queryDataBase:
    handler: src/database/query.hello
    events:
      - httpApi:
          path: /test/database
          method: post

  uploadAudio:
    handler: src/audio/uploadAudio.uploadAudio
    events:
      - httpApi:
          path: /audio/upload
          method: post

  scanProducts:
    handler: src/scans/scanProduct.scanProduct
    events:
      - httpApi:
          path: /scan/product
          method: post
