# "service" is the name of this project. This will also be added to your AWS resource names.
service: nanostores

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectTagging"
        - "s3:GetObject"
      Resource: "*"

plugins:
  - serverless-dotenv-plugin

package:
  individually: true # Packages each function individually
  exclude:
    - node_modules/** # Exclude initially to avoid redundancy
  include:
    - node_modules/** # Include the entire node_modules directory for each function
    - src/** # Include your source files

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /test
          method: get

  testRetrieveAudio:
    handler: src/audio/testRetrieveAudio.testReturnAudio
    events:
      - httpApi:
          path: /test/audio
          method: post

  queryDataBase:
    handler: src/database/queryDataBase.queryReceiver
    events:
      - httpApi:
          path: /database/query
          method: post

  uploadAudio:
    handler: src/audio/uploadAudio.uploadAudio
    events:
      - httpApi:
          path: /audio/upload
          method: post

  scanProducts:
    handler: src/scans/scanProduct.scanProduct
    events:
      - httpApi:
          path: /scan/product
          method: post

  transcriptAudio:
    handler: src/audio/audio.transcriptAudio
    events:
      - httpApi:
          path: /audio/transcript
          method: post

  getMetrics:
    handler: src/database/metrics.getMetrics
    events:
      - httpApi:
          path: /database/metrics
          method: get
