# "service" is the name of this project. This will also be added to your AWS resource names.
service: Zuricatos

provider:
  name: aws
  runtime: python3.12
  region: us-east-2
  environment:
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectTagging"
        - "s3:GetObject"
      Resource: "*"

plugins:
  - serverless-dotenv-plugin

functions:
  hello:
    handler: src/audio/receiveAudio.receiveAudio
    events:
      - httpApi:
          path: /receive/audio
          method: post

  testReturnAudio:
    handler: src/audio/testReturnAudio.testReturnAudio
    events:
      - httpApi:
          path: /test/obtain/audio
          method: get

  testProcessAudio:
    handler: src/audio/audioLambda.lambda_handler
    events:
      - httpApi:
          path: /test/transcript/audio
          method: get

  cleanAudio:
    handler: src/audio/cleanAudio.cleanAudio
    events:
      - httpApi:
          path: /audio/clean
          method: post

  createProducts:
    handler: src/database/productos.create
    events:
      - httpApi:
          path: /products/create
          method: post

  getProducts:
    handler: src/database/productos.read
    events:
      - httpApi:
          path: /products/get/{id}
          method: get

  updatedProductsQuantity:
    handler: src/database/productos.update_cantidad
    events:
      - httpApi:
          path: /products/update/quantity/{id}
          method: patch

  deleteProduct:
    handler: src/database/productos.delete
    events:
      - httpApi:
          path: /products/delete/{id}
          method: delete

  getUsers:
    handler: src/database/usuarios.read
    events:
      - httpApi:
          path: /users/get/{id}
          method: get
